GET http://localhost:9090 HTTP/1.1
Content-Type: application/json

nice to meet you!

###

GET http://localhost:9090/goodbye HTTP/1.1
Content-Type: application/json

exit!

###

POST http://localhost:9090 HTTP/1.1
Content-Type: application/json

{
  "name": "John"
}

###

GET http://localhost:9090/products HTTP/1.1
Content-Type: application/json


###

POST http://localhost:9090/products HTTP/1.1
Content-Type: application/json

{
  "id": "123",
  "name": "Frappe",
  "description": "A delicious drink"
}